import {
    Button,
    GroupBox,
    ComboBox,
    VerticalBox,
    HorizontalBox,
    GridBox,
    LineEdit,
    Switch
} from "std-widgets.slint";
import { IntEdit } from "../components/int_edit.slint";
import { Page } from "page.slint";
import { ApplicationGlobal, GameType } from "../globals.slint";

export enum UpdateCheckStatus {
    Error,
    UpdateAvailable,
    NoUpdate
}

export struct UpdateCheckResult {
    status: UpdateCheckStatus,
    message: string
}

export component HomePage inherits Page {
    title: @tr("Home");
    alignment: start;

    callback set_lr2_path();
    callback show_new_player_window();
    callback player_change(current-player: string);
    callback delete_player(player: string);
    callback check_for_openlr2_updates(current-version: string) -> UpdateCheckResult;

    GroupBox {
        title: @tr("Player");
        HorizontalBox {
            players := ComboBox {
                model: ApplicationGlobal.players;
                current-index <=> ApplicationGlobal.selected_player;
                selected(current-player) => {root.player_change(current-player)};
            }
            LineEdit {
                input-type: password;
                placeholder-text: @tr("Password");
                text <=> ApplicationGlobal.password;
            }
            Button {
                text: @tr("+");
                clicked => { root.show_new_player_window() }
                Tooltip {
                    text: @markdown("\{@tr("Add player")}");
                }
            }
            Button {
                text: @tr("-");
                clicked => {root.delete_player(players.current-value)}
                Tooltip {
                    text: @markdown("\{@tr("Remove player")}");
                }
            }
        }
    }

    GroupBox {
        title: @tr("Resolution");
        GridBox {
            IntEdit {
                min: 0;
                max: 9999;
                placeholder-text: "X";
                max-width: 50px;
                value <=> ApplicationGlobal.window_x;
            }
            Text {
                text: "x";
                vertical-alignment: center;
            }
            IntEdit {
                min: 0;
                max: 9999;
                placeholder-text: "Y";
                max-width: 50px;
                value <=> ApplicationGlobal.window_y;
            }
            HorizontalLayout {
                alignment: end;
                ComboBox {
                    model: {
                        if (ApplicationGlobal.gametype == GameType.OpenLR2) {
                            [@tr("Fullscreen"), @tr("Windowed"), @tr("Borderless Fullscreen")]
                        } else {
                            [@tr("Fullscreen"), @tr("Windowed")]
                        }
                    }
                    current-index <=> ApplicationGlobal.screenmode;
                }
            }
        }
    }

    GroupBox {
        title: @tr("LR2 path");
        VerticalLayout {
            HorizontalBox {
                LineEdit {
                    enabled: false;
                    text: ApplicationGlobal.lr2_path;
                }
                Button {
                    text: @tr("Set LR2 Path");
                    clicked => { root.set_lr2_path() }
                }
            }
            HorizontalLayout {
                alignment: start;
                StyledText {
                    default-font-size: 0.8rem;
                    text: {
                        if (ApplicationGlobal.gametype == GameType.LR2) {
                            return @markdown("*__<u>\{@tr("Loaded binary")}:</u>__ LR2 version \{ApplicationGlobal.gameversion}*");
                        } else if (ApplicationGlobal.gametype == GameType.OpenLR2) {
                            return @markdown("*__<u>\{@tr("Loaded binary")}:</u>__ OpenLR2 version \{ApplicationGlobal.gameversion}*");
                        }
                        return @markdown("*\{@tr("Unknown binary loaded, proceed with caution!")}*");
                    };
                }

                if (ApplicationGlobal.gametype == GameType.OpenLR2): HorizontalLayout {
                    // Separator
                    Text {
                        font-size: 0.8rem;
                        text: " | ";
                    }

                    StyledText {
                        default-font-size: 0.8rem;
                        text: @markdown("*[\{@tr("Check for updates...")}](update-check)*");
                        link-clicked(link) => {
                            if (link == "update-check") {
                                let res = root.check_for_openlr2_updates(ApplicationGlobal.gameversion);
                                if (res.status == UpdateCheckStatus.Error) {
                                    self.text = @markdown("*\{@tr("An error occurred")}: \{res.message}*");
                                    reset_update_text.start();
                                }
                                else if (res.status == UpdateCheckStatus.NoUpdate) {
                                    self.text = @markdown("*\{@tr("No updates available")}*");
                                    reset_update_text.start();
                                }
                                else if (res.status == UpdateCheckStatus.UpdateAvailable) {
                                    self.text = @markdown("*\{@tr("Update available")}: [\{res.message}](https://github.com/GOMazk/OpenLR2/releases/tag/\{res.message})*");
                                }
                            } else {
                                Platform.open-url(link);
                            }
                        };

                        reset_update_text := Timer {
                            interval: 5s;
                            running: false;
                            triggered() => {
                                self.running = false;
                                parent.text = @markdown("*[\{@tr("Check for updates...")}](update-check)*");
                            }
                        }
                    }
                }
            }
        }
    }

    GroupBox {
        title: @tr("Misc");
        HorizontalBox {
            VerticalBox {
                Switch {
                    text: @tr("Disable score saving");
                    checked <=> ApplicationGlobal.disable_score_save;
                }
                Switch {
                    text: @tr("Enable song preview");
                    checked <=> ApplicationGlobal.preview;
                }
                HorizontalLayout {
                    alignment: start;
                    spacing: 10px;
                    Text {
                        vertical-alignment: center;
                        text: @tr("Database reload type");
                    }
                    ComboBox {
                        width: 150px;
                        model: [@tr("Manual"), @tr("Auto Type 1"), @tr("Auto Type 2")];
                        current-index <=> ApplicationGlobal.autoreload;
                    }
                }
            }
        }
    }
}
