import {
    Button,
    HorizontalBox,
    GroupBox,
    VerticalBox,
} from "std-widgets.slint";

import { JukeboxListView } from "../components/jukebox.slint";

import { Page } from "page.slint";
import { ApplicationGlobal } from "../globals.slint";

export component JukeboxPage inherits Page {
    title: @tr("Jukebox");
    
    callback jukebox_add();
    callback jukebox_del(selected-item: int);

    GroupBox {
        VerticalBox {
            HorizontalLayout {
            StyledText {
                vertical-alignment: center;
                //text: @markdown("*\{@tr("Drag and drop folders to add BMS paths.")}*");
            }
            HorizontalBox {
                alignment: end;
                Button {
                    text: "Add";
                    clicked => {root.jukebox_add()};
                }
                Button {
                    text: "Delete";
                    clicked => {root.jukebox_del(jukebox.current-item)};
                    enabled: jukebox.current-item != -1;
                }
            }
        }
            DropArea {
                // TODO: folder drag and drop (when it's implemented in Slint)
                jukebox := JukeboxListView {
                    model: ApplicationGlobal.jukebox_paths;
                }
            }
        }
    }
}
