import {
    GroupBox,
    ComboBox,
    Switch, GridBox,
} from "std-widgets.slint";

import { Page } from "page.slint";
import { ApplicationGlobal } from "../globals.slint";

export component OpenLR2Page inherits Page {
    title: @tr("OpenLR2 options");
    alignment: start;

    GroupBox {
        title: @tr("System");

        GridBox {
            Row {
                Text {
                    vertical-alignment: center;
                    text: @tr("Default skin resolution type");
                }
                ComboBox {
                    model: [@tr("SD"), @tr("HD"), @tr("FHD")];
                    current-index <=> ApplicationGlobal.resolution;
                }
            }
            Row {
                Text {
                    vertical-alignment: center;
                    text: @tr("Fullscreen filter type");
                }
                ComboBox {
                    model: [@tr("Bilinear"), @tr("Nearest"), @tr("CRT")];
                    current-index <=> ApplicationGlobal.fullscreenfilter;
                }
            }
            Row {
                Switch {
                    text: @tr("Stretch fullscreen to screen");
                    checked <=> ApplicationGlobal.fullscreenfitstretch;
                }
            }
        }
    }

    GroupBox {
        title: @tr("Play");

        GridBox {
            Row {
                Switch {
                    text: @tr("Gauge Auto Shift");
                    checked <=> ApplicationGlobal.gaugeautoshift;
                }
            }
        }
    }

    GroupBox {
        title: @tr("Network");

        HorizontalLayout {
            alignment: start;
            spacing: 10px;
            Text {
                vertical-alignment: center;
                text: @tr("Display IR");
            }
            ComboBox {
                model: ApplicationGlobal.customirs;
                current-index <=> ApplicationGlobal.selectedir_index;
                current-value <=> ApplicationGlobal.display_ir;
            }
        }
    }
}