import { Palette } from "std-widgets.slint";

export enum GameType {
    Unknown, LR2, OpenLR2
}

export global ApplicationGlobal {
    out property <string> window_title: "LR2 launcher";

    // Home page
    in property <[string]> players;
    in-out property <int> selected_player;
    in-out property <string> password;
    in-out property <string> lr2_path;
    in-out property <int> window_x;
    in-out property <int> window_y;
    in-out property <int> screenmode;
    in-out property <int> autoreload;
    in-out property <bool> disable_score_save;
    in-out property <bool> preview;

    // Jukebox
    in property <[StandardListViewItem]> jukebox_paths;

    // Play
    in-out property <int> hsmin;
    in-out property <int> hsmax;
    in-out property <int> hsmargin;
    in-out property <int> shuttermargin;
    in-out property <int> basespeed;
    in-out property <bool> folderlamp;

    in-out property <bool> folder_random;
    in-out property <bool> folder_favorite;
    in-out property <bool> folder_ignored;
    in-out property <bool> folder_top10;
    in-out property <bool> folder_level;
    in-out property <bool> folder_cleartype;
    in-out property <bool> folder_playrank;
    in-out property <bool> folder_insanebms;

    in-out property <int> searchmax;
    in-out property <int> poorbga;
    in-out property <int> inputinterval;

    // System
    in-out property <bool> vsync;
    in-out property <int> audiooutput;
    in property <[string]> drivers;
    in-out property <int> selecteddriver;
    in-out property <int> bufferlength;
    in-out property <bool> disablefmod;

    // OpenLR2-specific options
    in-out property <int> resolution;
    in-out property <int> fullscreenfilter;
    in-out property <bool> fullscreenfitstretch;
    in-out property <bool> gaugeautoshift;
    in property <[string]> customirs;
    in-out property <int> selectedir_index;
    in-out property <string> display_ir;

    // Launcher settings
    in-out property <bool> darkmode;
    in-out property <int> language;
    in property <GameType> gametype;
    in property <string> gameversion;
}