import {
    HomePage,
    PlayOptionsPage,
    SystemOptionsPage,
    JukeboxPage,
} from "pages/pages.slint";
import { SideBar } from "side_bar.slint";
import { Button, ComboBox, Palette, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { ApplicationGlobal, GameType } from "globals.slint";
import { OpenLR2Page } from "pages/openlr2_page.slint";

export { Palette, ColorScheme }
export { ApplicationGlobal }
export { NewUser } from "new_user.slint";

export component App inherits Window {
    preferred-width: 800px;
    preferred-height: 650px;
    default-font-family: "Segoe UI";
    title: ApplicationGlobal.window_title;
    //icon: @image-url("../../logo/slint-logo-small-light.png");

    callback audio_type_change();
    callback set_lr2_path();
    callback jukebox_add();
    callback jukebox_del(selected-item: int);
    callback show_new_player_window();
    callback player_change(current-player: string);
    callback delete_player(player: string);
    callback launch_game();

    HorizontalLayout {
        side-bar := SideBar {
            accessible-role: navigation;
            accessible-label: @tr("Sidebar");
            title: @tr("LR2 launcher");
            model: {
                if (ApplicationGlobal.gametype == GameType.OpenLR2) {
                    [
                        @tr("Menu" => "Home"),
                        @tr("Menu" => "Jukebox"),
                        @tr("Menu" => "Play options"),
                        @tr("Menu" => "System options"),
                        @tr("Menu" => "OpenLR2 options")
                    ]
                } else {
                    [
                        @tr("Menu" => "Home"),
                        @tr("Menu" => "Jukebox"),
                        @tr("Menu" => "Play options"),
                        @tr("Menu" => "System options")
                    ]
                }
            };
            Button {
                text: @tr("Start game");
                primary: true;
                enabled: ApplicationGlobal.jukebox_paths.length != 0;
                clicked => {root.launch_game()};

                if ApplicationGlobal.jukebox_paths.length == 0: Tooltip {
                    text: @markdown("\{@tr("Jukebox is empty!")}");
                }
            }
        }

        VerticalLayout {
            accessible-role: main;
            accessible-label: @tr("Content");

            if(side-bar.current-item == 0): HomePage {
                set_lr2_path => {root.set_lr2_path()};
                show_new_player_window => {root.show_new_player_window()};
                player_change(current-player) => {root.player_change(current-player)};
                delete_player(player) => {root.delete_player(player)};
            }
            if(side-bar.current-item == 1): JukeboxPage { 
                jukebox_add => {root.jukebox_add()};
                jukebox_del(selected-item) => {root.jukebox_del(selected-item)};
            }
            if(side-bar.current-item == 2): PlayOptionsPage { }
            if(side-bar.current-item == 3): SystemOptionsPage { audio_type_change => {root.audio_type_change();} }
            if(side-bar.current-item == 4 && ApplicationGlobal.gametype == GameType.OpenLR2): OpenLR2Page { }
        }
    }

    VerticalBox {
        y: parent.height - 4.5rem;
        x: 0;
        width: side-bar.width;
        alignment: start;

        ComboBox {
            model: ["English", "日本語", "한국인"];
            current-index <=> ApplicationGlobal.language;
        }
    }
}
