name: build

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Add standard library source
      run: rustup component add rust-src --toolchain nightly-x86_64-pc-windows-msvc
    - name: Build
      run: cargo release
    - name: Run UPX
      uses: crazy-max/ghaction-upx@v4
      with:
        version: latest
        files: |
          target/release/lr2-launcher.exe
        args: -9
    - name: Upload artifact
      uses: actions/upload-artifact@v7.0.1
      with:
        path: target/release/lr2-launcher.exe
        archive: false
